export const LOCATIONS = {
  williamsburg: {
    id: "williamsburg",
    name: "Williamsburg",
    label: "The Original · Est. 1980",
    address: "627 Merrimac Trail",
    city: "Williamsburg, VA 23185",
    phone: "(757) 253-1080",
    flagship: true,
    toastOrderUrl: "https://order.toasttab.com/online/shortys-diner-627-merrimac-trl",
    doordashUrl: "https://www.doordash.com/store/shortys-diner-williamsburg-460667/2140855/",
  },
  yorktown: {
    id: "yorktown",
    name: "Yorktown",
    label: "Now Open",
    address: "6500 George Washington Memorial Hwy A",
    city: "Yorktown, VA 23692",
    phone: "(757) 867-8777",
    flagship: false,
    toastOrderUrl: "https://order.toasttab.com/online/shortys-diner-yorktown-6500-george-washington-memorial-highway",
    doordashUrl: "https://www.doordash.com/store/shortys-diner-yorktown-24714824/",
  },
  richmond: {
    id: "richmond",
    name: "Richmond",
    label: "Now Open",
    address: "5625 W Broad St",
    city: "Richmond, VA 23230",
    phone: "(804) 308-2070",
    flagship: false,
    toastOrderUrl: "https://shortysdinerbroad.toast.site/order/shortys-diner-rva-5625-west-broad-street",
    doordashUrl: "https://www.doordash.com/store/shortys-diner-rva-richmond-1532498/",
  },
  stlouis: {
    id: "stlouis",
    city: "St. Louis",
    address: "12004 Lackland Rd",
    cityState: "St. Louis, MO 63146",
    neighborhood: "Westport",
    phone: "(314) 392-9232",
    toastUrl: "",
    flagship: false,
    doordashUrl: "https://www.doordash.com/store/shortys-diner-saint-louis-41733676/",
  },
};
